profiles/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r'^(?P<username>[\w.@+-]+)/$',
        views.profile,
        name='profile'
    ),
]

pystagram/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

from photos.views import hello
from photos.views import detail
from photos.views import create


urlpatterns = [
    url(r'^hello/$', hello),
    url(r'^photos/(?P<pk>[0-9]+)/$', detail, name='detail'),
    url(r'^photos/upload/$', create, name='create'),
    url(r'^users/', include('profiles.urls')),

    url(r'^admin/', admin.site.urls),
    url(
        r'^accounts/login/',
        auth_views.login,
        name='login',
        kwargs={
            'template_name': 'login.html'
        }
    ),
    url(
        r'^accounts/logout/',
        auth_views.logout,
        name='logout',
        kwargs={
            'next_page': settings.LOGIN_URL,
        }

    ),
]

urlpatterns += static('/upload_files/', document_root=settings.MEDIA_ROOT)

photos/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse_lazy
from django.conf import settings


class Photo(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    image = models.ImageField(upload_to='%Y/%m/%d/orig')
    filtered_image = models.ImageField(upload_to='%Y/%m/%d/filtered')
    content = models.TextField(max_length=500, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at', '-pk', )

    def delete(self, *args, **kwargs):
        self.image.delete()
        self.filtered_image.delete()
        super(Photo, self).delete(*args, **kwargs)

    def get_absolute_url(self):
        url = reverse_lazy('detail', kwargs={'pk': self.pk})
        return url

photos/forms.py
from __future__ import unicode_literals

from django import forms

from .models import Photo


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ('image', 'content', )

photos/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from .models import Photo
from .forms import PhotoForm


def hello(request):
    return HttpResponse('안녕하세요!')


def detail(request, pk):
    # photo = Photo.objects.get(pk=pk)
    photo = get_object_or_404(Photo, pk=pk)

    messages = (
        '<p>{pk}번 사진 보여줄게요</p>'.format(pk=photo.pk),
        '<p>주소는 {url}</p>'.format(url=photo.image.url),
        '<p><img src="{url}" /></p>'.format(url=photo.image.url),
    )
    return HttpResponse('\n'.join(messages))


@login_required
def create(request):
    if request.method == "GET":
        form = PhotoForm()
    elif request.method == "POST":
        form = PhotoForm(request.POST, request.FILES)

        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.save()

            return redirect(obj)

    ctx = {
        'form': form,
    }

    return render(request, 'edit.html', ctx)

profiles/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model


def profile(request, username):
    User = get_user_model()
    user = get_object_or_404(User, username=username)
    ctx = {
        'user': user,
    }
    return render(request, 'profile.html', ctx)

photos/templates/edit.html
{% extends 'layout.html' %}

{% block content %}
<form
    method="POST"
    action=""
    enctype="multipart/form-data"
>
    {% csrf_token %}
    {{ form.as_p }}

    <p>
        <button type="submit">저장</button>
    </p>
</form>

{% endblock %}

photos/templates/layout.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <title>{% block page_title %}Pystagram{% endblock %}</title>
    <meta charset="utf-8" />
    <script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
</head>

<body>
{% block content %}{% endblock %}
</body>

</html>

photos/templates/login.html
{% extends "layout.html" %}

{% block content %}

{% if form.errors %}
<p>ID나 비밀번호가 일치하지 않습니다.</p>
{% endif %}

<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<input type="hidden" name="next" value="{{ next }}" />

{{ form.as_p }}

<button type="submit">로그인</button>
</form>

{% endblock %}

profiles/templates/profile.html
{% extends 'layout.html' %}

{% block content %}
<h1>{{ user.username }}님의 프로필 페이지</h1>

<ul>
    {% for photo in user.photo_set.all %}
        <li><img src="{{photo.image.url}}" /></li>
    {% empty %}
        <li>게시한 사진이 없습니다.</li>
    {% endfor %}
</ul>

{% endblock %}